### ISSUE TITLE
Generating images

### ISSUE THREAD

**Issue by mahimachowdarym** [mattiasxu/VQVAE-2#1]
Hi,

Can you helping me with generating images. I am new to this and I don't know how to generate images from the train model.

**Comment by mattiasxu** [comment]
Sorry, it's been a while since I've been working on this.

But if you have managed to train it, you can generate new images by using the trained autoregressive model. That means, you need to start with an empty input, and it will generate the next "pixel" and you have to feed it back iteratively until it has generated the whole latent image. After that you can feed it into the decoder and hopefully an okay image has been generated
